### ISSUE TITLE
Progress bar goes beyond 100%.

### ISSUE THREAD

**Issue by smzm** [MortezaBashsiz/CFScanner#124]
**Describe the bug**

Super useful script. 
But there is an issue. When `progress bar of main IPs` reached 100% it's not the end and number in percentage go further and pass the 100%. obviously, Searching still continues.

**To Reproduce**
Run script as describe in `readme.md` file.

**Expected behavior**
Finishing job at `100%`.

**Screenshots**
![image](https://user-images.githubusercontent.com/39596095/221217245-bc0675eb-bc40-48ad-89e8-878ed26cd082.png)

**Desktop (please complete the following information):**
 - OS: Arch-WSL2
 - [Latest Commit](https://github.com/MortezaBashsiz/CFScanner/commit/d706cb18419962c31703b269e712d87412f1f72f)

**Comment by MortezaBashsiz** [comment]
Thank you so much
I will check it

**Comment by ImanIranNejad** [comment]
i think its because of number threads.i used 128 for testing and after about 10 mins its the progress bar :


FAILED 104.16.58.234
FAILED 104.16.58.238
FAILED 104.16.58.236
FAILED 104.16.58.233
| Progress bar of main IPs: [=======================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================>







                          ] 1966.66%

**Comment by MortezaBashsiz** [comment]
Could both of you plz share how you run the script?
I mean the exact command that you run with all arguments

**Comment by ImanIranNejad** [comment]
Thx for update and i was doing this commad:
Bash cfScanner.sh 128 4 ./ClientConfig.json 500
