### ISSUE TITLE
MacOS or windows?

### ISSUE THREAD

**Issue by theduckperson** [MortezaBashsiz/CFScanner#75]
is there any way to run the script on macOS or windows?

thanks.

**Comment by MortezaBashsiz** [comment]
Hi
This is compatible with macOS but in some cases there may be issues

**Comment by naderjafari** [comment]
Hi Morteza
It is better If we have a Docker version of this script to run cross platform ...

**Comment by theduckperson** [comment]
> 

first of all, im not a computer expert.
i install [homebrew](https://brew.sh/) on my mac.
then i clone and run the script but the prompt says i dont have "parallel". i install it with brew. then script needed gtimeout. i couldn't install it because it was not in brew database.

**Comment by alimalek71** [comment]
> > 
> 
> first of all, im not a computer expert. i install [homebrew](https://brew.sh/) on my mac. then i clone and run the script, but the prompt says i dont have `parallel`. i install it with brew. then script needed gtimeout. i couldn't install it because it was not in brew database.

Use blew command to add `gtimeout`:

`brew install coreutils`

**Comment by theduckperson** [comment]
> > > 
> > 
> > 
> > first of all, im not a computer expert. i install [homebrew](https://brew.sh/) on my mac. then i clone and run the script, but the prompt says i dont have `parallel`. i install it with brew. then script needed gtimeout. i couldn't install it because it was not in brew database.
> 
> Use blew command to add `gtimeout`:
> 
> `brew install coreutils`

thanks! now script run without errors.
after reading config, i got
`could not get url curl -s https://asnlookup.com/asn/AS13335/`
but the progress is continued.

**Comment by alimalek71** [comment]
Could you manually check that you could open the link `https://asnlookup.com/asn/AS13335/`? 

The usage of this site is for getting `CloudFlare IP Ranges` to start its scan over them. 

If you can't open the link in your browser, you need to find the root cause of it.

You should see this page:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15885307/219948456-99b72b5d-1a33-4b70-b38a-a67d42d6cec9.png">

@MortezaBashsiz If it's possible, maybe adding offline data for the script will help to pass this step faster.

**Comment by MortezaBashsiz** [comment]
This page https://asnlookup.com/asn/AS13335/ is also offline
If you do not have access to the page script will use the local file cf.local.iplist as list
